import { CategoryType } from '../types';

interface DefaultCategory {
  name: string;
  name_hr: string;
  type: CategoryType;
  icon: string;
  color: string;
  is_recurring: number;
  default_amount: number;
  due_day: number | null;
  is_active: number;
  is_system: number;
}

export const DEFAULT_CATEGORIES: DefaultCategory[] = [
  // === INCOME ===
  {
    name: 'salary',
    name_hr: 'Plaća',
    type: 'income',
    icon: 'cash',
    color: '#2E7D32',
    is_recurring: 1,
    default_amount: 279,
    due_day: null,
    is_active: 1,
    is_system: 1,
  },
  {
    name: 'rent_income',
    name_hr: 'Stanarine',
    type: 'income',
    icon: 'home-city',
    color: '#388E3C',
    is_recurring: 1,
    default_amount: 153,
    due_day: null,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'pickleball',
    name_hr: 'Pickleball plaća',
    type: 'income',
    icon: 'tennis',
    color: '#43A047',
    is_recurring: 1,
    default_amount: 11,
    due_day: null,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'tenant_bills',
    name_hr: 'Računi podstanari',
    type: 'income',
    icon: 'receipt',
    color: '#4CAF50',
    is_recurring: 1,
    default_amount: 53,
    due_day: null,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'other_income',
    name_hr: 'Ostalo',
    type: 'income',
    icon: 'plus-circle',
    color: '#66BB6A',
    is_recurring: 0,
    default_amount: 0,
    due_day: null,
    is_active: 1,
    is_system: 0,
  },
  // === EXPENSES ===
  {
    name: 'mortgage',
    name_hr: 'Stambeni kredit',
    type: 'expense',
    icon: 'home',
    color: '#C62828',
    is_recurring: 1,
    default_amount: 87.26,
    due_day: 28,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'personal_loan',
    name_hr: 'Nenamjenski kredit',
    type: 'expense',
    icon: 'bank',
    color: '#D32F2F',
    is_recurring: 1,
    default_amount: 55.04,
    due_day: 28,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'credit_card',
    name_hr: 'Kreditna kartica',
    type: 'expense',
    icon: 'credit-card',
    color: '#E53935',
    is_recurring: 1,
    default_amount: 8.09,
    due_day: 28,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'electricity',
    name_hr: 'Struja',
    type: 'expense',
    icon: 'lightning-bolt',
    color: '#F57F17',
    is_recurring: 1,
    default_amount: 25,
    due_day: 15,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'web_tools',
    name_hr: 'Web alati',
    type: 'expense',
    icon: 'web',
    color: '#1565C0',
    is_recurring: 1,
    default_amount: 7.30,
    due_day: 17,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'insurance',
    name_hr: 'Osiguranje',
    type: 'expense',
    icon: 'shield',
    color: '#6A1B9A',
    is_recurring: 1,
    default_amount: 5.31,
    due_day: 25,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'fuel',
    name_hr: 'Gorivo',
    type: 'expense',
    icon: 'gas-station',
    color: '#E65100',
    is_recurring: 1,
    default_amount: 30,
    due_day: null,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'food',
    name_hr: 'Hrana',
    type: 'expense',
    icon: 'food',
    color: '#BF360C',
    is_recurring: 0,
    default_amount: 0,
    due_day: null,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'daily_life',
    name_hr: 'Život (dnevno)',
    type: 'expense',
    icon: 'calendar-today',
    color: '#880E4F',
    is_recurring: 1,
    default_amount: 124,
    due_day: null,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'health',
    name_hr: 'Zdravlje',
    type: 'expense',
    icon: 'medical-bag',
    color: '#C2185B',
    is_recurring: 0,
    default_amount: 0,
    due_day: null,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'phone',
    name_hr: 'Mobitel',
    type: 'expense',
    icon: 'cellphone',
    color: '#AD1457',
    is_recurring: 1,
    default_amount: 0,
    due_day: null,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'entertainment',
    name_hr: 'Zabava',
    type: 'expense',
    icon: 'party-popper',
    color: '#7B1FA2',
    is_recurring: 0,
    default_amount: 0,
    due_day: null,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'clothing',
    name_hr: 'Odjeća',
    type: 'expense',
    icon: 'tshirt-crew',
    color: '#512DA8',
    is_recurring: 0,
    default_amount: 0,
    due_day: null,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'tax',
    name_hr: 'Porez',
    type: 'expense',
    icon: 'file-document',
    color: '#4527A0',
    is_recurring: 0,
    default_amount: 8.50,
    due_day: null,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'other_expense',
    name_hr: 'Ostalo',
    type: 'expense',
    icon: 'dots-horizontal',
    color: '#37474F',
    is_recurring: 0,
    default_amount: 0,
    due_day: null,
    is_active: 1,
    is_system: 0,
  },
  // === SAVINGS ===
  {
    name: 'savings_main',
    name_hr: 'Štednja',
    type: 'savings',
    icon: 'piggy-bank',
    color: '#1565C0',
    is_recurring: 1,
    default_amount: 0,
    due_day: null,
    is_active: 1,
    is_system: 1,
  },
  {
    name: 'emergency_fund',
    name_hr: 'Hitni fond',
    type: 'savings',
    icon: 'lifebuoy',
    color: '#0277BD',
    is_recurring: 0,
    default_amount: 0,
    due_day: null,
    is_active: 1,
    is_system: 0,
  },
  {
    name: 'vacation_fund',
    name_hr: 'Odmor',
    type: 'savings',
    icon: 'beach',
    color: '#0288D1',
    is_recurring: 0,
    default_amount: 0,
    due_day: null,
    is_active: 1,
    is_system: 0,
  },
];
